In [2]:
import pandas as pd

In [ ]:
# df = pd.read_csv("raw_data.csv")
# print(df)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
import pandas as pd

# Load dataframe again (important)
df = pd.read_csv("raw_data.csv")

# remove extra spaces in column names
df.columns = df.columns.str.strip()

# tax column
df["tax"] = df["income"].apply(
    lambda x: "20%" if x >= 50000 else "10%"
)

# gender mapping
gender_map = {"Male":"M","Female":"F","Unknown":"U"}
df["gender"] = df["gender"].map(gender_map)

# assign
df = df.assign(new_income = df["income"] * 1.1) 

#replace
df["country"] = df["country"].replace("USA","US")
df

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0

In [24]:
df

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [ ]:
df.columns=["Id","Name","Age","Country","Gender","Income","Tax","New_Index"]
df
df.rename(columns={"Gender":"Gender"})
df.rename(index={2:"Two"})

df.sort_values("Income")
df.sort_values("Income",ascending=False)
df = df.fillna(50)
sorted_df = df.sort_values(["Income","Age"])
df
sorted_df.sort_index()
sorted_df.reset_index(drop=True)

#Ranking
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False,method="max")
sorted_df

    Id          Name   Age Country Gender   Income  Tax  New_Index  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%       50.0     11.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%    49500.0     10.0
3    3          Alex  50.0      US      U  47000.0  10%    51700.0      9.0
5    5        Li Wei  27.0   China      M  51000.0  20%    56100.0      8.0
0    1      John Doe  29.0      US      M  55000.0  20%    60500.0      7.0
1    1      John Doe  29.0      US      M  55000.0  20%    60500.0      7.0
10  10   Emily Davis  31.0      US     50  58000.0  20%    63800.0      5.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%    68200.0      4.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%    68200.0      4.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%    74800.0      2.0
6    6            50  45.0   India      F  73000.0  20%    80300.0      1.0